### ISSUE TITLE
Сложнопостроенные ссылки прямо в вызове запроса к серверу

### ISSUE THREAD

**Issue by UniBreakfast** [SeYmUr867543210/youtube-telegram_bot#5]
https://github.com/SeYmUr867543210/youtube-telegram_bot/blob/5ea13b38666f2495d8c350def7821bb8aa2346a0/server.js#L25

https://github.com/SeYmUr867543210/youtube-telegram_bot/blob/5ea13b38666f2495d8c350def7821bb8aa2346a0/server.js#L37

Вынесите сформированные ссылки в отдельные константы пожалуйста. И просто используйте их здесь.

**Comment by SeYmUr867543210** [comment]
done

**Comment by UniBreakfast** [comment]
Что "done"?

**Comment by UniBreakfast** [comment]
Лучше бы вместо "done" вставили ссылку-врезку на исправление, чтобы я мог сразу это увидеть, а не искал, пытаясь увидеть изменения ещё до того, как вы их зальёте в репозиторий.
